kind: pipeline
name: default

steps:

- name: build docker image
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t weaver-scala-sbt-yarn:latest docker/

  # Compile the code/run tests
- name: build
  image: weaver-scala-sbt-yarn:latest
  pull: if-not-exists
  commands:
  - apt install nodejs -y
  - sbt ci
  - echo Built $(cat version)
  environment:
    COURSIER_CACHE: .cache/coursier
  volumes:
    - name: sbt-cache
      path: /root/.sbt



# Compile the code/run tests
- name: build
  image: weaver-scala-sbt-yarn:latest
  pull: if-not-exists
  commands:
  - sbt ci
  - echo Built $(cat version)
  environment:
    COURSIER_CACHE: .cache/coursier
  volumes:
    - name: sbt-cache
      path: /root/.sbt

# Publish maven artifacts (on tag push)
- name: publish-to-sonatype
  image: weaver-scala-sbt-yarn:latest
  pull: if-not-exists
  commands:
  - echo $PGP_SECRET | base64 --decode | gpg --import --no-tty --batch --yes
  - echo Releasing version $(cat version)
  - sbt release
  environment:
    COURSIER_CACHE: .cache/coursier
    SONATYPE_USER:
      from_secret: sonatype_username
    SONATYPE_PASSWORD:
      from_secret: sonatype_password
    PGP_SECRET:
      from_secret: pgp_secret
    PGP_PASSPHRASE:
      from_secret: pgp_passphrase
  when:
    ref:
      - refs/tags/v*
  volumes:
  - name: sbt-cache
    path: /root/.sbt

- name: publish-site
  image: weaver-scala-sbt-yarn:latest
  pull: if-not-exists
  commands:
  - mkdir -p $HOME/.ssh
  - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
  - sbt 'docs/docusaurusPublishGhpages'
  - echo done publishing website
  environment:
    COURSIER_CACHE: .cache/coursier
    GIT_USER: $DRONE_COMMIT_AUTHOR
    GITHUB_DEPLOY_KEY:
      from_secret: github_deploy_public_key
  when:
    ref:
      - refs/tags/v*
  volumes:
    - name: sbt-cache
      path: /root/.sbt

volumes:
- name: sbt-cache
  temp: {}
- name: dockersock
  host:
    path: /var/run/docker.sock

---
kind: secret
name: sonatype_username
data: zwYme1IjiRRozAUUdVQwjlBJFfKpfRqQpZI/cp7AdgnavGSd
---
kind: secret
name: sonatype_password
data: ZZMmOIfeOdqSZfMkQbdCkamaOIO/HebT7aadI37GVYvoBtod+2lQXy39eGnKUQPCYPtNHMqIcgmiedv8ZGUVnRxn8JNQ7DTK
---
kind: secret
name: pgp_passphrase
data: b230qO9iNBwetch1kZafgydRC/LNfJGFgAj/GiOyBKEJYglBACXv3sTfbKBDbuntIWSCAVHM
