kind: pipeline
name: default

steps:

# Compile the code/run tests
- name: build
  image: keynmol/weaver-scala-sbt-yarn:latest
  commands:
  - sbt ci
  - echo Built $(cat version)
  environment:
    COURSIER_CACHE: .cache/coursier
    SBT_OPTS: "-XX:+UseG1GC -XX:MaxMetaspaceSize=2g -Xms1g -Xmx2g -Xss2M -XX:+CMSClassUnloadingEnabled"
  volumes:
    - name: sbt-cache
      path: /root/.sbt
    - name: intellij-cache
      path: /root/.weaver-intellijPluginIC

# Publish maven artifacts (on tag push)
- name: publish-to-sonatype
  image: keynmol/weaver-scala-sbt-yarn:latest
  commands:
  - echo $PGP_SECRET | base64 --decode | gpg --import --no-tty --batch --yes
  - echo Releasing version $(cat version)
  - sbt release
  environment:
    COURSIER_CACHE: .cache/coursier
    SBT_OPTS: "-XX:+UseG1GC -XX:MaxMetaspaceSize=2g -Xms1g -Xmx2g -Xss2M -XX:+CMSClassUnloadingEnabled"
    SONATYPE_USER:
      from_secret: sonatype_username
    SONATYPE_PASSWORD:
      from_secret: sonatype_password
    PGP_SECRET:
      from_secret: pgp_secret
    PGP_PASSPHRASE:
      from_secret: pgp_passphrase
  when:
    ref:
      - refs/tags/v*
  volumes:
  - name: sbt-cache
    path: /root/.sbt

# Uploads intellij plugin to the github release
- name: publish-intellij-plugin
  image: keynmol/weaver-scala-sbt-yarn:latest
  commands:
  - sbt packageIntellijPlugin
  - amm scripts/releasePlugin.sc $(cat intellijPlugin)
  environment:
    COURSIER_CACHE: .cache/coursier
    SBT_OPTS: "-XX:+UseG1GC -XX:MaxMetaspaceSize=2g -Xms1g -Xmx2g -Xss2M -XX:+CMSClassUnloadingEnabled"
    GITHUB_TOKEN:
      from_secret: github_api_token
  when:
    ref:
      - refs/tags/v*
  volumes:
    - name: sbt-cache
      path: /root/.sbt
    - name: intellij-cache
      path: /root/.weaver-intellijPluginIC

- name: publish-site
  image: keynmol/weaver-scala-sbt-yarn:latest
  commands:
  - mkdir -p $HOME/.ssh
  - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
  - sbt 'docs/docusaurusPublishGhpages'
  - echo done publishing website
  environment:
    COURSIER_CACHE: .cache/coursier
    SBT_OPTS: "-XX:+UseG1GC -XX:MaxMetaspaceSize=2g -Xms1g -Xmx2g -Xss2M -XX:+CMSClassUnloadingEnabled"
    GIT_USER: $DRONE_COMMIT_AUTHOR
    GITHUB_DEPLOY_KEY:
      from_secret: github_deploy_key
  when:
    ref:
      - refs/tags/v*
  volumes:
    - name: sbt-cache
      path: /root/.sbt

volumes:
- name: sbt-cache
  temp: {}
- name: intellij-cache
  temp: {}
