// format: off
addSbtPlugin("ch.epfl.scala"        % "sbt-scalafix"                  % "0.9.33")
addSbtPlugin("org.scala-js"         % "sbt-scalajs"                   % "1.7.1")
addSbtPlugin("com.eed3si9n"         % "sbt-projectmatrix"             % "0.9.0")
addSbtPlugin("com.jsuereth"         % "sbt-pgp"                       % "2.1.1")
addSbtPlugin("com.dwijnand"         % "sbt-dynver"                    % "4.1.1")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"                  % "3.9.11")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"                  % "2.4.6")
addSbtPlugin("org.scalameta"        % "sbt-mdoc"                      % "2.3.0")
addSbtPlugin("com.eed3si9n"         % "sbt-buildinfo"                 % "0.10.0")
