// format: off
addSbtPlugin("ch.epfl.scala"        % "sbt-scalafix"                  % "0.9.28")
addSbtPlugin("org.scala-js"         % "sbt-scalajs"                   % "1.5.1")
addSbtPlugin("com.eed3si9n"         % "sbt-projectmatrix"             % "0.8.0")
addSbtPlugin("com.jsuereth"         % "sbt-pgp"                       % "2.1.1")
addSbtPlugin("com.dwijnand"         % "sbt-dynver"                    % "4.1.1")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"                  % "3.9.7")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"                  % "2.4.2")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"                 % "1.8.1")
addSbtPlugin("org.scalameta"        % "sbt-mdoc"                      % "2.2.21")
addSbtPlugin("com.eed3si9n"         % "sbt-buildinfo"                 % "0.10.0")
